name: ci

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to the container registry server
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_SERVER }}   # User-defined repository secret variable. Value: ghcr.io
          username: ${{ github.repository_owner }}   # Pre-defined variable by GitHub Actions
          password: ${{ secrets.GITHUB_TOKEN }}      # Pre-defined variable by GitHub Actions
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.event_name == 'push' }}   # Only push Docker images to the registry server on the push event 
          tags: |-
            ${{ secrets.REGISTRY_SERVER }}/${{ github.repository }}:latest
            ${{ secrets.REGISTRY_SERVER }}/${{ github.repository }}:build-${{ vars.GITHUB_RUN_NUMBER }}
