name: hello-world

on: [push, pull_request]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - env:
          NAME: ${{ secrets.NAME }}
        run: echo "Hello, $NAME!"
