name: hello-world

on: [push, pull_request]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hello, World!"
      - run: cat requirements.txt
